/*
    Se crean las secuencias necesarias para poder hacer que las llaves primarias de todas las tablas sean
    autoincremnetables
 */

CREATE SEQUENCE seq_matricula_academica START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_detalle_matricula START WITH 1 INCREMENT BY 1 NOCACHE

CREATE SEQUENCE seq_nota START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_auditoria_operacional START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_historial_academico START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_estudiante START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_docente START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_configuracion_nota_grupo START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_auditoria_riesgo START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_estudio START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_institucion_educativa START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_grupo START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_clase START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_departamento START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_municipio START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_tipo_programa START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_tipo_asignatura START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_programa_academico START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_facultad START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_sede START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_periodo_academico START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_tipo_nota START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_nivel_riesgo START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_asignatura START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_asignatura_especial START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE SEQUENCE seq_aula START WITH 1 INCREMENT BY 1 NOCACHE;

