CREATE TABLESPACE TS_ALTA_CONCURRENCIA
DATAFILE 'C:\oraclexe\app\oracle\oradata\xe\ts_alta_conc01.dbf' 
SIZE 1500M 
AUTOEXTEND ON NEXT 100M MAXSIZE 10G 
EXTENT MANAGEMENT LOCAL 
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_BAJA_CONCURRENCIA
DATAFILE 'C:\oraclexe\app\oracle\oradata\xe\ts_baja_conc01.dbf'
SIZE 40M
AUTOEXTEND ON NEXT 10M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_SOLO_LECTURA
DATAFILE 'C:\oraclexe\app\oracle\oradata\xe\ts_solo_lectura01.dbf'
SIZE 50M
AUTOEXTEND OFF
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_INDICES
DATAFILE 'C:\oraclexe\app\oracle\oradata\xe\ts_indices01.dbf'
SIZE 350M
AUTOEXTEND ON NEXT 50M MAXSIZE 1G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE TS_TEMPORALES
TEMPFILE 'C:\oraclexe\app\oracle\oradata\xe\ts_temp01.dbf'
SIZE 450M
AUTOEXTEND ON NEXT 50M MAXSIZE 1500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

CREATE UNDO TABLESPACE TS_UNDO
DATAFILE 'C:\oraclexe\app\oracle\oradata\xe\ts_undo01.dbf'
SIZE 400M
AUTOEXTEND ON NEXT 50M MAXSIZE 2G
RETENTION GUARANTEE;
