CREATE USER DATACAMPUS IDENTIFIED BY admin123
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE TO DATACAMPUS;
GRANT CREATE VIEW TO DATACAMPUS;
GRANT CREATE SEQUENCE TO DATACAMPUS;
GRANT CREATE TRIGGER TO DATACAMPUS;
GRANT CREATE PROCEDURE TO DATACAMPUS;
GRANT CREATE TYPE TO DATACAMPUS;